sonar.projectKey=awesome
sonar.projectName=awesome
sonar.sourceEncoding=UTF-8
sonar.java.source=8
sonar.sources=awesome-dto/src/main/java,awesome-web/src/main/java
sonar.tests=awesome-web/src/test/java
sonar.java.binaries=awesome-dto/target/classes,awesome-web/target/classes
sonar.coverage.jacoco.xmlReportPaths=awesome-web/target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=awesome-web/target/surefire-reports
