spring.profiles.active=dev
server.servlet.context-path=/awesome
spring.jpa.open-in-view=false

management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health,info
management.server.port=${APP_PORT:${server.port:8080}}
management.endpoints.web.base-path=/actuator
